using System;
using System.Collections.Generic;
using System.Net;
using System.Threading;

namespace Internal.Telemetry;

/// <summary>
/// The ambient facts about the request currently being served.
/// </summary>
/// <remarks>
/// Application code raises a counter with one call and no plumbing; it does not, and
/// should not, have to thread a request object down to whatever noticed the thing worth
/// counting. So the peer address, the classification of the traffic, the request id and
/// the resolved route ride the ambient context instead.
/// </remarks>
public sealed class RequestContext
{
    /// <summary>Correlation id for this request, generated by the middleware.</summary>
    public string RequestId { get; init; } = string.Empty;

    /// <summary>
    /// Address of the peer that opened the connection, as read from the connection and
    /// from nowhere else. Null when what we were handed turned out to be a caller's
    /// claim rather than a socket address.
    /// </summary>
    public IPAddress? PeerAddress { get; init; }

    /// <summary>
    /// Whatever the deployment calls the client address, forwarded values included.
    /// Description only: nothing is ever decided on it.
    /// </summary>
    public string? ClientIp { get; init; }

    /// <summary>True when the peer sits in one of the estate's generated-traffic ranges.</summary>
    public bool Synthetic { get; init; }

    /// <summary>Route template being served, once routing has resolved one.</summary>
    public string? Route { get; set; }

    /// <summary>Authenticated principal, once the application has declared one.</summary>
    public string? AuthSubject { get; set; }

    /// <summary>
    /// Attributes contributed while the request runs. The middleware merges them into
    /// the single record it exports, so one request stays one record.
    /// </summary>
    public List<ParamEntry> ExtraParams { get; } = new();

    /// <summary>The peer address as it travels on a record.</summary>
    public string? PeerIp => SourceMatcher.Format(PeerAddress);
}

/// <summary>
/// Ambient access to <see cref="RequestContext"/>.
/// </summary>
/// <remarks>
/// <para>
/// The store is an <see cref="AsyncLocal{T}"/>, which is what the execution context
/// carries across <c>await</c>, across <c>Task.Run</c> and across the thread-pool work
/// a handler queues, so a counter raised four call frames deep still says which request
/// provoked it and from which peer.
/// </para>
/// <para>
/// One case does not flow: work started from a context where the execution context was
/// suppressed, or continued on a thread that only kept the <c>HttpContext</c>. For that
/// there is a fallback: the middleware also files the context under
/// <see cref="ItemsKey"/> in <c>HttpContext.Items</c>, and <see cref="Resolver"/> is
/// pointed at an <c>IHttpContextAccessor</c> when one is registered.
/// </para>
/// </remarks>
public static class TelemetryContext
{
    private static readonly AsyncLocal<RequestContext?> Store = new();

    /// <summary>Key the middleware files the context under, for the fallback path.</summary>
    public const string ItemsKey = "internal.telemetry.request";

    /// <summary>
    /// Optional second source consulted when the ambient store is empty. Installed by
    /// the hosting extensions when an <c>IHttpContextAccessor</c> is available.
    /// </summary>
    public static Func<RequestContext?>? Resolver { get; set; }

    /// <summary>The context of the request being served, or null outside one.</summary>
    public static RequestContext? Current
    {
        get
        {
            RequestContext? ambient = Store.Value;
            if (ambient is not null)
            {
                return ambient;
            }

            Func<RequestContext?>? resolver = Resolver;
            if (resolver is null)
            {
                return null;
            }

            try
            {
                return resolver();
            }
            catch (Exception)
            {
                // A fallback that throws is a fallback that fails a request. Never.
                return null;
            }
        }
    }

    /// <summary>Put a context in scope for the remainder of the current logical flow.</summary>
    public static void Set(RequestContext? context) => Store.Value = context;

    /// <summary>Take the context out of scope again.</summary>
    public static void Clear() => Store.Value = null;

    /// <summary>
    /// Carry the facts of the request in flight into work that runs somewhere else.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Most work needs nothing: the execution context follows <c>await</c>, a
    /// <c>ConfigureAwait(false)</c> continuation on a pool thread, and
    /// <c>Task.Run</c>, so a counter raised inside any of those already says which
    /// request provoked it. Two cases do not follow, and both are silent:
    /// <c>ExecutionContext.SuppressFlow</c>, and a long-lived worker that was started
    /// before the request and is handed the work through a queue.
    /// </para>
    /// <para>
    /// Wrap the callable and it keeps them:
    /// <code>
    /// queue.Post(Telemetry.Bind(() =&gt; RebuildIndex(tenant)));
    /// </code>
    /// The wrapper re-enters the same context object rather than a copy, so one bound
    /// callable can safely run on several workers at once.
    /// </para>
    /// </remarks>
    /// <param name="body">The work to carry the context into.</param>
    /// <returns>A wrapper that puts the current context in scope while it runs.</returns>
    public static Action Bind(Action body)
    {
        if (body is null)
        {
            throw new ArgumentNullException(nameof(body));
        }

        RequestContext? captured = Current;
        return () => Run(captured, body);
    }

    /// <summary>Bind a callable that produces a value.</summary>
    /// <typeparam name="T">What the work produces.</typeparam>
    /// <param name="body">The work to carry the context into.</param>
    /// <returns>A wrapper that puts the current context in scope while it runs.</returns>
    public static Func<T> Bind<T>(Func<T> body)
    {
        if (body is null)
        {
            throw new ArgumentNullException(nameof(body));
        }

        RequestContext? captured = Current;
        return () =>
        {
            RequestContext? previous = Store.Value;
            Store.Value = captured;
            try
            {
                return body();
            }
            finally
            {
                Store.Value = previous;
            }
        };
    }

    /// <summary>Bind asynchronous work.</summary>
    /// <param name="body">The work to carry the context into.</param>
    /// <returns>A wrapper that puts the current context in scope while it runs.</returns>
    public static Func<Task> Bind(Func<Task> body)
    {
        if (body is null)
        {
            throw new ArgumentNullException(nameof(body));
        }

        RequestContext? captured = Current;
        return async () =>
        {
            RequestContext? previous = Store.Value;
            Store.Value = captured;
            try
            {
                await body().ConfigureAwait(false);
            }
            finally
            {
                Store.Value = previous;
            }
        };
    }

    /// <summary>
    /// Run a delegate with a context in scope and restore whatever was there before.
    /// Useful for a queue consumer or a socket server that wants the same facts on the
    /// records raised by the work it dispatches.
    /// </summary>
    public static void Run(RequestContext? context, Action body)
    {
        if (body is null)
        {
            throw new ArgumentNullException(nameof(body));
        }

        RequestContext? previous = Store.Value;
        Store.Value = context;
        try
        {
            body();
        }
        finally
        {
            Store.Value = previous;
        }
    }
}
